app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

api_transaction_list:
    path:    /api/transaction/list
    methods: [GET]
    defaults: { _controller: AppBundle:Default:transactionList}