security:
    providers:
        in_memory:
            memory: ~

    encoders:
        AppBundle\Entity\User\User: sha256

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false

    access_control:
        - { path: /api, roles: [ IS_AUTHENTICATED_FULLY ] }
